config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/balance'

  resources :outcomes
  resources :outcomes
  resources :incomes
  get 'static_pages/home', as: :home
  post 'static_pages/home' => 'static_pages#saldar'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'sessions/new'

  resources :kids

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root :to => "sessions#new"

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_action :user_logged, only: [:home]
  before_action :admin_logged, only: [:balance]

  def home
    @cash = Kid.sum(:pay)
    @act = Income.where(owner: "inscripciones").take
    @diff = Kid.sum(:pay) - @act.amount
    @nkids = Kid.count
  end

  def saldar
    @cash = Kid.sum(:pay)
    Income.where(owner: "inscripciones").limit(1).update_all(amount: @cash)
    redirect_to home_path and return
  end

  def about
  end

  def contact
  end

  def balance
    @inc = Income.sum(:amount)
    @outc = Outcome.sum(:amount)
    @nkids = Kid.count
    @pkids = Kid.where(pay: 90).count
    @bal = @inc - @outc
  end

  def user_logged
  	unless user_logged_in?
  		redirect_to root_url and return
  	end
  end

  def admin_logged
    unless admin_logged_in?
      redirect_to home_path and return
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<h1>Acerca de</h1>
<p class="text-info">Pagina de inscripciones a la escuela biblica de verano, en la iglesia Renovacion Cristiana, 2016.</p>
<p class="text-muted">Para mas informacion acerca de esta pagina favor de contactar a Daniel Monzalvo.</p>

app/views/static_pages/balance.html.erb
<h4>Resumen al día de la EBDV 2016</h4>
<div class="jumbotron">
	<h3>Resumen</h3>
	<div class="row">
		<div class="container col-md-3">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<div class="huge"><%= @bal %></div>
					<div class="descripcion">Balance</div>
				</div>
			</div>
		</div>
		<div class="container col-md-3">
			<div class="panel panel-success">
				<div class="panel-heading">
					<div class="huge"><%= @inc %></div>
					<div class="descripcion">Ingresos</div>
				</div>
				<div class="panel-footer">
					<%= link_to "Ver detalles", incomes_path %>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<div class="container col-md-3">
			<div class="panel panel-danger">
				<div class="panel-heading">
					<div class="huge"><%= @outc %></div>
					<div class="descripcion">Costos</div>
				</div>
				<div class="panel-footer">
					<%= link_to "Ver detalles", outcomes_path %>
					<div class="clearfix"></div>
				</div>
			</div>
		</div>
		<div class="container col-md-3">
			<div class="panel panel-info">
				<div class="panel-heading">
					<div class="info-panel">Niños inscritos: <%= @nkids %></div>
					<div class="info-panel">Niños saldados: <%= @pkids %></div>
				</div>
				<div class="panel-footer">
					<%= link_to "Ver detalles", kids_path %>
					<div class="clearfix"></div>
				</div>
			</div>
			<p></p>
			<p></p>
		</div>
	</div>
</div>

app/views/static_pages/contact.html.erb
<center><h1>Renovacion Cristiana</h1></center>
<div class="text-info">
<p>Camino a Santa Lucia n°98,</p>
<p>Col. Olivar del Conde 1a seccion,</p>
<p>Del. Alvaro Obregon</p>
<p>Mexico, Ciudad de Mexico</p>
<p>Telefono: 55 93 18 38</p>
</div>
</br>
<a href="http://rc.org.mx/" ><p class="text-primary">Visita nuestra página WEB</p></a>

app/views/static_pages/home.html.erb
<h4>Bienvenido a la platorma de inscripciones de la EBDV 2016</h4>
<div class="jumbotron">
	<h3>Resumen</h3>
	<div class="row">
		<div class="container col-md-4">
			<p>N° niños inscritos: <%= @nkids %></p>
		</div>
		<div class="container col-md-4">
			<p>Total de ingresos: <%= @cash %></p>
		</div>
		<div class="container col-md-4">
			<p>Diferencia <%= @diff %></p>
			<%= button_to "Saldar", :method => "saldar" , class:"btn  btn-default"%>
		</div>
	</div>
</div>
<div>
	<%= button_to "Inscribir", new_kid_path , :method => "get" , class:"btn  btn-default"%>
</br>
	<%= button_to "Buscar", kids_path, :method => "get", class:"btn btn-default"%>
</div>