config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/balance'

  resources :outcomes
  resources :outcomes
  resources :incomes
  get 'static_pages/home', as: :home
  post 'static_pages/home' => 'static_pages#saldar'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'sessions/new'

  resources :kids

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root :to => "sessions#new"

end

app/models/kid.rb
class Kid < ActiveRecord::Base
	validates :name, presence: true, length: {minimum: 2, maximum: 20}
	validates :lastf, presence:true
	validates :age, presence:true, numericality: {only_integer:true, :greater_than_or_equal_to => 3, :less_than_or_equal_to =>13}
	validates :address, presence:true
	validates :phone, presence:true, numericality: {only_integer:true, :greater_than => 0}
	validates :celphone, numericality: {only_integer:true,:greater_than => 0}
	validates :pay, presence:true, numericality: {only_integer:true ,:greater_than_or_equal_to => 0, :less_than_or_equal_to =>90}
	validates :pick_up, presence:true
end

app/controllers/kids_controller.rb
class KidsController < ApplicationController
  before_action :set_kid, only: [:show, :edit, :update, :destroy]
  before_action :logged_in

  # GET /kids
  # GET /kids.json
  def index
    @kids = Kid.order(age: :asc, name: :asc).all
  end

  # GET /kids/1
  # GET /kids/1.json
  def show
  end

  # GET /kids/new
  def new
    @kid = Kid.new
  end

  # GET /kids/1/edit
  def edit
  end

  # POST /kids
  # POST /kids.json
  def create
    @kid = Kid.new(kid_params)

    respond_to do |format|
      if @kid.save
        format.html { redirect_to @kid, notice: 'Kid was successfully created.' }
        format.json { render :show, status: :created, location: @kid }
      else
        format.html { render :new }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /kids/1
  # PATCH/PUT /kids/1.json
  def update
    respond_to do |format|
      if @kid.update(kid_params)
        format.html { redirect_to @kid, notice: 'Kid was successfully updated.' }
        format.json { render :show, status: :ok, location: @kid }
      else
        format.html { render :edit }
        format.json { render json: @kid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /kids/1
  # DELETE /kids/1.json
  def destroy
    @kid.destroy
    respond_to do |format|
      format.html { redirect_to kids_url, notice: 'Kid was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def logged_in
      unless user_logged_in?
        redirect_to root_url
      end
    end

    def set_kid
      @kid = Kid.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def kid_params
      params.require(:kid).permit(:name, :lastf, :lastm, :age, :nmother, :nfather, :address, :phone, :exphone, :celphone, :pay, :alergy, :pick_up)
    end
end

app/helpers/kids_helper.rb
module KidsHelper
end

app/views/kids/_form.html.erb
<%= form_for(@kid) do |f| %>
  <% if @kid.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@kid.errors.count, "error") %> prohibited this kid from being saved:</h2>

      <ul>
      <% @kid.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label(:name, "Nombre*") %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label(:lastf, "Apellido Paterno*") %><br>
    <%= f.text_field :lastf %>
  </div>
  <div class="field">
    <%= f.label(:lastm, "Apellido Materno") %><br>
    <%= f.text_field :lastm %>
  </div>
  <div class="field">
    <%= f.label(:age, "Edad*") %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label(:nmother, "Nombre Madre") %><br>
    <%= f.text_field :nmother %>
  </div>
  <div class="field">
    <%= f.label(:nfather, "Nombre Padre") %><br>
    <%= f.text_field :nfather %>
  </div>
  <div class="field">
    <%= f.label(:address, "Dirección*") %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label(:phone, "Teléfono*") %><br>
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label(:exphone, "Teléfono adicional") %><br>
    <%= f.number_field :exphone %>
  </div>
  <div class="field">
    <%= f.label(:celphone, "Celular") %><br>
    <%= f.number_field :celphone %>
  </div>
  <div class="field">
    <%= f.label(:pick_up, "¿Quién recoge?*") %><br>
    <%= f.text_field :pick_up %>
  </div>
  <div class="field">
    <%= f.label(:alergy, "Alergias") %><br>
    <%= f.text_area :alergy %>
  </div>
  <div class="field">
    <%= f.label(:pay, "Monto Pagado*") %><br>
    <%= f.number_field :pay %>
  </div>

  <div class="actions">
    <%= f.submit 'Crear', class: "btn btn-default btn-primary" %>
  </div>
<% end %>

app/views/kids/edit.html.erb
<h1>Editing Kid</h1>

<%= render 'form' %>

<%= link_to 'Atrás', home_path, class:"btn btn-default" %>

app/views/kids/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Niños</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido Paterno</th>
      <th>Apellido Materno</th>
      <th>Edad</th>
      <th>Pagado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @kids.each do |kid| %>
      <tr>
        <td><%= kid.name %></td>
        <td><%= kid.lastf %></td>
        <td><%= kid.lastm %></td>
        <td><%= kid.age %></td>
        <td><%= kid.pay %></td>
        <td><%= link_to 'Ver', kid %></td>
        <td><%= link_to 'Editar', edit_kid_path(kid) %></td>
        <td><%= link_to 'Quitar', kid, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<center><%= link_to 'Inscribir', new_kid_path, class:"btn btn-default"%></center>

app/views/kids/new.html.erb
<h1>Nuevo Nino</h1>

<%= render 'form' %>

app/views/kids/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @kid.name %>
</p>

<p>
  <strong>Apellido Paterno:</strong>
  <%= @kid.lastf %>
</p>

<p>
  <strong>Apellido Materno:</strong>
  <%= @kid.lastm %>
</p>

<p>
  <strong>Pagado:</strong>
  <%= @kid.pay %>
</p>

<p>
  <strong>Edad:</strong>
  <%= @kid.age %>
</p>

<p>
  <strong>Nombre Madre:</strong>
  <%= @kid.nmother %>
</p>

<p>
  <strong>Nombre Padre:</strong>
  <%= @kid.nfather %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @kid.address %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @kid.phone %>
</p>

<p>
  <strong>Telefono adicional:</strong>
  <%= @kid.exphone %>
</p>

<p>
  <strong>Celular:</strong>
  <%= @kid.celphone %>
</p>

<p>
  <strong>Alergias:</strong>
  <%= @kid.alergy %>
</p>

<p>
  <strong>Recoge:</strong>
  <%= @kid.pick_up %>
</p>
<center>
<%= link_to 'Editar', edit_kid_path(@kid), class:"btn btn-default"%> &nbsp;
<%= link_to 'Regresar', home_path, class:"btn btn-default" %>
</br>
</br>
<%= button_to 'Nuevo niño', new_kid_path, method:'get', class:"btn btn-default btn-primary" %>
</center>