config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/balance'

  resources :outcomes
  resources :outcomes
  resources :incomes
  get 'static_pages/home', as: :home
  post 'static_pages/home' => 'static_pages#saldar'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'sessions/new'

  resources :kids

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root :to => "sessions#new"

end

app/models/outcome.rb
class Outcome < ActiveRecord::Base
end

app/controllers/outcomes_controller.rb
class OutcomesController < ApplicationController
  before_action :set_outcome, only: [:show, :edit, :update, :destroy]
  before_action :admin_logged

  # GET /outcomes
  # GET /outcomes.json
  def index
    @outcomes = Outcome.all
  end

  # GET /outcomes/1
  # GET /outcomes/1.json
  def show
  end

  # GET /outcomes/new
  def new
    @outcome = Outcome.new
  end

  # GET /outcomes/1/edit
  def edit
  end

  # POST /outcomes
  # POST /outcomes.json
  def create
    @outcome = Outcome.new(outcome_params)

    respond_to do |format|
      if @outcome.save
        format.html { redirect_to @outcome, notice: 'Outcome was successfully created.' }
        format.json { render :show, status: :created, location: @outcome }
      else
        format.html { render :new }
        format.json { render json: @outcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /outcomes/1
  # PATCH/PUT /outcomes/1.json
  def update
    respond_to do |format|
      if @outcome.update(outcome_params)
        format.html { redirect_to @outcome, notice: 'Outcome was successfully updated.' }
        format.json { render :show, status: :ok, location: @outcome }
      else
        format.html { render :edit }
        format.json { render json: @outcome.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outcomes/1
  # DELETE /outcomes/1.json
  def destroy
    @outcome.destroy
    respond_to do |format|
      format.html { redirect_to outcomes_url, notice: 'Outcome was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def admin_logged
      unless admin_logged_in?
        redirect_to home_path and return
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_outcome
      @outcome = Outcome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def outcome_params
      params.require(:outcome).permit(:amount, :owner, :description)
    end
end

app/helpers/outcomes_helper.rb
module OutcomesHelper
end

app/views/outcomes/_form.html.erb
<%= form_for(@outcome) do |f| %>
  <% if @outcome.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outcome.errors.count, "error") %> prohibieron que fuera registrado:</h2>

      <ul>
      <% @outcome.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount, 'Cantidad' %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :owner, '¿Para quién?' %><br>
    <%= f.text_field :owner %>
  </div>
  <div class="field">
    <%= f.label :description, 'Descripción' %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit 'OK', class:"btn btn-default btn-primary" %>
  </div>
<% end %>

app/views/outcomes/edit.html.erb
<h1>Editar Costo</h1>

<%= render 'form' %>

<%= button_to 'Cancelar', outcomes_path , class:"btn btn-default btn-primary" %>

app/views/outcomes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Costos</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Cantidad</th>
      <th>Dueño</th>
      <th>Descripcion</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @outcomes.each do |outcome| %>
      <tr>
        <td><%= outcome.amount %></td>
        <td><%= outcome.owner %></td>
        <td><%= outcome.description %></td>
        <td><%= link_to 'Editar', edit_outcome_path(outcome) %></td>
        <td><%= link_to 'Eliminar', outcome, method: :delete, data: { confirm: 'Seguro?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nuevo Costo', new_outcome_path, class:"btn btn-default" %>

app/views/outcomes/new.html.erb
<h1>Nuevo Costo</h1>

<%= render 'form' %>

<div class="row">
	<div class= "col-sm-4">
		<%= button_to 'Cancelar', outcomes_path , method: 'get',class:"btn btn-default" %>
	</div>
	<div class= "col-sm-8">
	</div>
</div>

app/views/outcomes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @outcome.amount %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @outcome.owner %>
</p>

<p>
  <strong>Description:</strong>
  <%= @outcome.description %>
</p>

<%= link_to 'Edit', edit_outcome_path(@outcome) %> |
<%= link_to 'Back', outcomes_path %>