config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/balance'

  resources :outcomes
  resources :outcomes
  resources :incomes
  get 'static_pages/home', as: :home
  post 'static_pages/home' => 'static_pages#saldar'

  get 'static_pages/about'

  get 'static_pages/contact'

  get 'sessions/new'

  resources :kids

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  root :to => "sessions#new"

end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<nav>
		<ul>
			<li><%= link_to "Acerca de", static_pages_about_path %></li>
			<li><%= link_to "Contacto", static_pages_contact_path %></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	  <div class="container">
		      <%= link_to "EBDV 2016 - Sumergidos",home_path, id: "logo" %>

		      <% if user_logged_in? %>
		      	<%= render 'layouts/menu' %>
		      	<h2 class="title">Bienvenido - <%= current_user.name %></h2> 	
		      <% end %>
	  </div>
</header>

app/views/layouts/_menu.html.erb
<nav>
	<ul class="nav navbar-nav navbar-right">
		<% if admin_logged_in? %>
			<li><%= link_to "Resumen", static_pages_balance_path %></li>
			<li><%= link_to "Inscripciones", home_path %></li>
			<li><%= link_to "Ingresos", incomes_path %></li>
			<li><%= link_to "Costos", outcomes_path %></li>
		<% end %>
		<li><%= link_to "Cerrar sesión", logout_path, method: "delete" %></li>
	</ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Inscripciones EBDV 2016</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container"> 
		<% flash.each do |message_type, message| %>
			<div class="alert alert-<%= message_type %>"><%=message %></div>
		<% end %>
		<div class ="container">
			<%= yield %>
		</div>
		<div>
			<%= render 'layouts/footer' %>
		</div>
	</div>

</body>
</html>